server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    refresh:
      enabled: true